### ISSUE TITLE
JSON Encoder does not marshal maps correctly

### ISSUE THREAD

**Issue by clbanning** [ugorji/go-msgpack#13]
maps are not encoded with commas - ',' - separating key:value pairs.

Would like to add a file with demo code - but here's test case without codecgen output:

first codecdemo.go:

package codecdemo

import (
	"github.com/ugorji/go/codec"
	"strconv"
	"time"
)

type MapVal struct {
	Name string
	Time time.Time
}

type Entry struct {
	Vals map[string]*MapVal
}

type Wrapper struct {
	Entries []*Entry
}

func Codecdemo() ([]byte, error) {
	w := new(Wrapper)
	w.Entries = make([]*Entry, 1)
	e := new(Entry)
	w.Entries[0] = e
	w.Entries[0].Vals = make(map[string]*MapVal, 0)

	for i := 0; i < 4; i++ {
		m := new(MapVal)
		m.Name = strconv.Itoa(i + 1)
		m.Time = time.Now()
		w.Entries[0].Vals[m.Name] = m
	}

	b := make([]byte, 0)
	h := new(codec.JsonHandle)
	enc := codec.NewEncoderBytes(&b, h)
	if err := enc.Encode(w); err != nil {
		return nil, err
	}

	return b, nil
}

now codecdemo_test.go:

package codecdemo

import (
	"encoding/json"
	"testing"
)

func TestCodecDemo(t *testing.T) {
	val, err := Codecdemo()
	if err != nil {
		t.Fatal(err)
	}

	m := new(Wrapper)
	if err = json.Unmarshal(val, m); err != nil {
		println("val:", string(val))
		t.Fatal(err)
	}

	println("val:", string(val))
}

**Comment by ugorji** [comment]
This library is now unsupported. I think you filed this in the wrong place.
